name = "homelab-maintenance-failover"
main = "worker.js"
compatibility_date = "2024-09-01"

# Route untuk mencakup domain utama dan semua subdomain
routes = [
  { pattern = "stevchrist.site/*", zone_name = "stevchrist.site" },
  { pattern = "*.stevchrist.site/*", zone_name = "stevchrist.site" }
]

[vars]
VERCEL_ORIGIN = "https://homelab-maintenance.vercel.app"
